<?php

namespace ContainerYj2YUNB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_T3nyaaoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.t3nyaao' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.t3nyaao'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'authenticationUtils' => ['privates', 'security.authentication_utils', 'getSecurity_AuthenticationUtilsService', true],
            'solicitudPagoRepository' => ['privates', 'App\\Repository\\SolicitudPagoRepository', 'getSolicitudPagoRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'authenticationUtils' => '?',
            'solicitudPagoRepository' => 'App\\Repository\\SolicitudPagoRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
