<?php

namespace ContainerYj2YUNB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YK0afhlService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.YK0afhl' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YK0afhl'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'formadePago' => ['privates', '.errored..service_locator.YK0afhl.App\\Entity\\FormadePago', NULL, 'Cannot autowire service ".service_locator.YK0afhl": it references class "App\\Entity\\FormadePago" but no such service exists.'],
            'formadePagoRepository' => ['privates', 'App\\Repository\\FormadePagoRepository', 'getFormadePagoRepositoryService', true],
        ], [
            'formadePago' => 'App\\Entity\\FormadePago',
            'formadePagoRepository' => 'App\\Repository\\FormadePagoRepository',
        ]);
    }
}
