<?php

namespace ContainerYj2YUNB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OLnHsf6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.oLnHsf6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.oLnHsf6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'servicio' => ['privates', '.errored..service_locator.oLnHsf6.App\\Entity\\Servicios', NULL, 'Cannot autowire service ".service_locator.oLnHsf6": it references class "App\\Entity\\Servicios" but no such service exists.'],
            'serviciosRepository' => ['privates', 'App\\Repository\\ServiciosRepository', 'getServiciosRepositoryService', true],
        ], [
            'servicio' => 'App\\Entity\\Servicios',
            'serviciosRepository' => 'App\\Repository\\ServiciosRepository',
        ]);
    }
}
