<?php

namespace ContainerYj2YUNB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7zS4ZIuService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7zS4ZIu' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7zS4ZIu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'asignarProductoaUserRepository' => ['privates', 'App\\Repository\\AsignarProductoaUserRepository', 'getAsignarProductoaUserRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'asignarProductoaUserRepository' => 'App\\Repository\\AsignarProductoaUserRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
