<?php

namespace ContainerYj2YUNB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getServiciosService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.7Kf.uLc.App\Entity\Servicios' shared service.
     *
     * @return \App\Entity\Servicios
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.7Kf.uLc": it references class "App\\Entity\\Servicios" but no such service exists.');
    }
}
