<?php

namespace ContainerYj2YUNB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSolicitarRecogida2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.cDTSNpE.App\Entity\SolicitarRecogida' shared service.
     *
     * @return \App\Entity\SolicitarRecogida
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.cDTSNpE": it references class "App\\Entity\\SolicitarRecogida" but no such service exists.');
    }
}
