<?php

namespace ContainerYj2YUNB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSolicitudPago2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.zoS76.G.App\Entity\SolicitudPago' shared service.
     *
     * @return \App\Entity\SolicitudPago
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.zoS76.G": it references class "App\\Entity\\SolicitudPago" but no such service exists.');
    }
}
