<?php

namespace ContainerYj2YUNB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVentaServicioService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Ky8bYL4.App\Entity\VentaServicio' shared service.
     *
     * @return \App\Entity\VentaServicio
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.Ky8bYL4": it references class "App\\Entity\\VentaServicio" but no such service exists.');
    }
}
