<?php

namespace ContainerQ44Qy5C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZjusBOMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZjusBOM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZjusBOM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'solicitarRecogida' => ['privates', '.errored..service_locator.ZjusBOM.App\\Entity\\SolicitarRecogida', NULL, 'Cannot autowire service ".service_locator.ZjusBOM": it references class "App\\Entity\\SolicitarRecogida" but no such service exists.'],
            'solicitarRecogidaRepository' => ['privates', 'App\\Repository\\SolicitarRecogidaRepository', 'getSolicitarRecogidaRepositoryService', true],
        ], [
            'solicitarRecogida' => 'App\\Entity\\SolicitarRecogida',
            'solicitarRecogidaRepository' => 'App\\Repository\\SolicitarRecogidaRepository',
        ]);
    }
}
