<?php

namespace ContainerQ44Qy5C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RmaCdUdService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rmaCdUd' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rmaCdUd'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'authenticationUtils' => ['privates', 'security.authentication_utils', 'getSecurity_AuthenticationUtilsService', true],
            'serviciosRepository' => ['privates', 'App\\Repository\\ServiciosRepository', 'getServiciosRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'authenticationUtils' => '?',
            'serviciosRepository' => 'App\\Repository\\ServiciosRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
