<?php

namespace ContainerQ44Qy5C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DBWWLc3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dBWWLc3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dBWWLc3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'authenticationUtils' => ['privates', 'security.authentication_utils', 'getSecurity_AuthenticationUtilsService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'ventaServicioRepository' => ['privates', 'App\\Repository\\VentaServicioRepository', 'getVentaServicioRepositoryService', true],
        ], [
            'authenticationUtils' => '?',
            'userRepository' => 'App\\Repository\\UserRepository',
            'ventaServicioRepository' => 'App\\Repository\\VentaServicioRepository',
        ]);
    }
}
