<?php

namespace ContainerQ44Qy5C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Hti9eIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Hti_9eI' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Hti_9eI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'serviciosRepository' => ['privates', 'App\\Repository\\ServiciosRepository', 'getServiciosRepositoryService', true],
        ], [
            'serviciosRepository' => 'App\\Repository\\ServiciosRepository',
        ]);
    }
}
