<?php

namespace ContainerQ44Qy5C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_04dMpwTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.04dMpwT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.04dMpwT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'authenticationUtils' => ['privates', 'security.authentication_utils', 'getSecurity_AuthenticationUtilsService', true],
            'solicitarRecogidaRepository' => ['privates', 'App\\Repository\\SolicitarRecogidaRepository', 'getSolicitarRecogidaRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'authenticationUtils' => '?',
            'solicitarRecogidaRepository' => 'App\\Repository\\SolicitarRecogidaRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
