<?php

namespace ContainerQ44Qy5C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DGIMHoRService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.DGIMHoR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.DGIMHoR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'ventaServicioRepository' => ['privates', 'App\\Repository\\VentaServicioRepository', 'getVentaServicioRepositoryService', true],
        ], [
            'ventaServicioRepository' => 'App\\Repository\\VentaServicioRepository',
        ]);
    }
}
