<?php

namespace ContainerQ44Qy5C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3HMCmHnService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3HMCmHn' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3HMCmHn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'formadePagoRepository' => ['privates', 'App\\Repository\\FormadePagoRepository', 'getFormadePagoRepositoryService', true],
        ], [
            'formadePagoRepository' => 'App\\Repository\\FormadePagoRepository',
        ]);
    }
}
