<?php

namespace ContainerQ44Qy5C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BCmDUCXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BCmDUCX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BCmDUCX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'asignarProductoaUser' => ['privates', '.errored..service_locator.BCmDUCX.App\\Entity\\AsignarProductoaUser', NULL, 'Cannot autowire service ".service_locator.BCmDUCX": it references class "App\\Entity\\AsignarProductoaUser" but no such service exists.'],
        ], [
            'asignarProductoaUser' => 'App\\Entity\\AsignarProductoaUser',
        ]);
    }
}
