<?php

namespace ContainerQ44Qy5C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAsignarProductoaUser2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.ZGGSTFo.App\Entity\AsignarProductoaUser' shared service.
     *
     * @return \App\Entity\AsignarProductoaUser
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.ZGGSTFo": it references class "App\\Entity\\AsignarProductoaUser" but no such service exists.');
    }
}
