<?php

namespace ContainerQ44Qy5C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFormadePagoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.ALnOESz.App\Entity\FormadePago' shared service.
     *
     * @return \App\Entity\FormadePago
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.ALnOESz": it references class "App\\Entity\\FormadePago" but no such service exists.');
    }
}
