<?php

namespace ContainerQ44Qy5C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVentaServicio2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.yCPTt6H.App\Entity\VentaServicio' shared service.
     *
     * @return \App\Entity\VentaServicio
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.yCPTt6H": it references class "App\\Entity\\VentaServicio" but no such service exists.');
    }
}
