<?php

namespace ContainerQ44Qy5C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVentaProductoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.PLzFt.0.App\Entity\VentaProducto' shared service.
     *
     * @return \App\Entity\VentaProducto
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.PLzFt.0": it references class "App\\Entity\\VentaProducto" but no such service exists.');
    }
}
